// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/bank/v1beta1/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CoinSpent is emitted whenever an address spends somes coins.
// This is a replacement for the original non-types event of the same name
type CoinSpent struct {
	Spender    string                                   `protobuf:"bytes,1,opt,name=spender,proto3" json:"spender,omitempty"`
	Amount     github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
	UpdatedBal github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=updatedBal,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"updatedBal"`
}

func (m *CoinSpent) Reset()         { *m = CoinSpent{} }
func (m *CoinSpent) String() string { return proto.CompactTextString(m) }
func (*CoinSpent) ProtoMessage()    {}
func (*CoinSpent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f584fe8577fc94b, []int{0}
}
func (m *CoinSpent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinSpent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinSpent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinSpent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinSpent.Merge(m, src)
}
func (m *CoinSpent) XXX_Size() int {
	return m.Size()
}
func (m *CoinSpent) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinSpent.DiscardUnknown(m)
}

var xxx_messageInfo_CoinSpent proto.InternalMessageInfo

func (m *CoinSpent) GetSpender() string {
	if m != nil {
		return m.Spender
	}
	return ""
}

func (m *CoinSpent) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CoinSpent) GetUpdatedBal() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.UpdatedBal
	}
	return nil
}

// CoinReceived is emitted whenever an address receives somes coins.
// This is a replacement for the original non-types event of the same name
type CoinReceived struct {
	Receiver   string                                   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount     github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
	UpdatedBal github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=updatedBal,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"updatedBal"`
}

func (m *CoinReceived) Reset()         { *m = CoinReceived{} }
func (m *CoinReceived) String() string { return proto.CompactTextString(m) }
func (*CoinReceived) ProtoMessage()    {}
func (*CoinReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f584fe8577fc94b, []int{1}
}
func (m *CoinReceived) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinReceived.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinReceived.Merge(m, src)
}
func (m *CoinReceived) XXX_Size() int {
	return m.Size()
}
func (m *CoinReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinReceived.DiscardUnknown(m)
}

var xxx_messageInfo_CoinReceived proto.InternalMessageInfo

func (m *CoinReceived) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *CoinReceived) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CoinReceived) GetUpdatedBal() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.UpdatedBal
	}
	return nil
}

func init() {
	proto.RegisterType((*CoinSpent)(nil), "cosmos.bank.v1beta1.CoinSpent")
	proto.RegisterType((*CoinReceived)(nil), "cosmos.bank.v1beta1.CoinReceived")
}

func init() { proto.RegisterFile("cosmos/bank/v1beta1/event.proto", fileDescriptor_5f584fe8577fc94b) }

var fileDescriptor_5f584fe8577fc94b = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x93, 0x56, 0x2a, 0xd4, 0x30, 0x85, 0x0e, 0x69, 0x07, 0xb7, 0xea, 0x54, 0x86, 0x3a,
	0xb4, 0xf0, 0x02, 0xa4, 0x6f, 0xd0, 0x6e, 0x2c, 0x28, 0x89, 0x4f, 0x21, 0x0a, 0xb1, 0xa3, 0xd8,
	0x89, 0xe0, 0x2d, 0x60, 0xe1, 0x21, 0x98, 0x79, 0x88, 0x8e, 0x15, 0x13, 0x13, 0xa0, 0xe4, 0x45,
	0x50, 0x62, 0x37, 0x62, 0x82, 0x85, 0x89, 0xc9, 0xe7, 0xf3, 0x77, 0xff, 0x7f, 0x3e, 0x1d, 0x1a,
	0x07, 0x5c, 0x24, 0x5c, 0x38, 0xbe, 0xc7, 0x62, 0xa7, 0x58, 0xf8, 0x20, 0xbd, 0x85, 0x03, 0x05,
	0x30, 0x49, 0xd2, 0x8c, 0x4b, 0x6e, 0x9d, 0x28, 0x80, 0xd4, 0x00, 0xd1, 0xc0, 0x68, 0xa8, 0x92,
	0xd7, 0x0d, 0xe2, 0x68, 0xa2, 0xb9, 0x8c, 0x70, 0x2b, 0x28, 0xa0, 0x15, 0x0c, 0x78, 0xc4, 0xf4,
	0xfb, 0x20, 0xe4, 0x21, 0x57, 0x75, 0x75, 0xa4, 0xb2, 0xd3, 0xc7, 0x0e, 0xea, 0xaf, 0x78, 0xc4,
	0x36, 0x29, 0x30, 0x69, 0x2d, 0xd1, 0x81, 0x48, 0x81, 0x51, 0xc8, 0x6c, 0x73, 0x62, 0xce, 0xfa,
	0xae, 0xfd, 0xfa, 0x32, 0x1f, 0x68, 0x9b, 0x4b, 0x4a, 0x33, 0x10, 0x62, 0x23, 0xb3, 0x88, 0x85,
	0xeb, 0x3d, 0x68, 0x05, 0xa8, 0xe7, 0x25, 0x3c, 0x67, 0xd2, 0xee, 0x4c, 0xba, 0xb3, 0xa3, 0xe5,
	0x90, 0xb4, 0x8d, 0x0b, 0xd8, 0x37, 0x4e, 0x6a, 0x0f, 0xf7, 0x6c, 0xfb, 0x3e, 0x36, 0x9e, 0x3f,
	0xc6, 0xb3, 0x30, 0x92, 0x37, 0xb9, 0x4f, 0x02, 0x9e, 0xe8, 0x3f, 0xe8, 0x63, 0x2e, 0x68, 0xec,
	0xc8, 0xfb, 0x14, 0x44, 0x53, 0x20, 0xd6, 0x5a, 0xda, 0x8a, 0x11, 0xca, 0x53, 0xea, 0x49, 0xa0,
	0xae, 0x77, 0x6b, 0x77, 0xff, 0xde, 0xe8, 0x9b, 0xfc, 0xf4, 0xa9, 0x83, 0x8e, 0xeb, 0xec, 0x1a,
	0x02, 0x88, 0x0a, 0xa0, 0xd6, 0x05, 0x3a, 0xcc, 0x54, 0xfc, 0xfb, 0x5c, 0x5a, 0xf2, 0xff, 0x0d,
	0xc6, 0x5d, 0x6d, 0x4b, 0x6c, 0xee, 0x4a, 0x6c, 0x7e, 0x96, 0xd8, 0x7c, 0xa8, 0xb0, 0xb1, 0xab,
	0xb0, 0xf1, 0x56, 0x61, 0xe3, 0xea, 0xf4, 0x47, 0xbd, 0x3b, 0xb5, 0xe5, 0x8d, 0xac, 0xdf, 0x6b,
	0x16, 0xef, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xca, 0xaa, 0x0b, 0xc0, 0x01, 0x03, 0x00, 0x00,
}

func (m *CoinSpent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinSpent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinSpent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedBal) > 0 {
		for iNdEx := len(m.UpdatedBal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UpdatedBal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Spender) > 0 {
		i -= len(m.Spender)
		copy(dAtA[i:], m.Spender)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Spender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CoinReceived) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinReceived) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinReceived) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdatedBal) > 0 {
		for iNdEx := len(m.UpdatedBal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UpdatedBal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CoinSpent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Spender)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.UpdatedBal) > 0 {
		for _, e := range m.UpdatedBal {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *CoinReceived) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.UpdatedBal) > 0 {
		for _, e := range m.UpdatedBal {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CoinSpent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinSpent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinSpent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedBal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedBal = append(m.UpdatedBal, types.Coin{})
			if err := m.UpdatedBal[len(m.UpdatedBal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinReceived) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinReceived: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinReceived: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedBal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedBal = append(m.UpdatedBal, types.Coin{})
			if err := m.UpdatedBal[len(m.UpdatedBal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
